# Generated by Django 3.2.12 on 2023-05-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Название события', max_length=128, unique=True, verbose_name='Событее'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(help_text='Название организации', max_length=128, unique=True, verbose_name='Организация'),
        ),
    ]
