version: '3.2'
services:
  events_db:
    image: postgres:13-alpine
    volumes:
      - events_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis_events:
    image: redis:alpine
    container_name: redis_events
    volumes:
      - redis_events:/redis_events/data
    restart: always
    ports:
      - 6379:6379



volumes:
  events_db:
  redis_events:


