# Generated by Django 3.2.12 on 2023-05-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
